Levelup
Teaching-projects/SZE-MOSZE-2020-TeamlessName pull request #6
Opened 2020-10-13 14:42 UTC by molmat

Player osztály, statikus kódanalízis, memory leak check hozzáadva

2020-10-14 12:39 UTC, oliverosz requested changes

2020-10-14 12:39 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: cppcheck *.cpp --enable=warning --output-file=checkreport.txt
`--enable=style,performance`

2020-10-14 12:39 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: valgrind --error-exitcode=1 ./a.out units/unit1.json units/unit2.json
Kell még a `--leak-check=full` is, különben nem mindent tekint errornak.

2020-10-14 12:39 UTC, oliverosz commented on Player.h
> +	void levelUp();
Nyilván nem okoz hibát, ha meghívják feleslegesen, de inkább ez ne legyen publikus.

2020-10-14 12:39 UTC, oliverosz commented on main.cpp
> +		BaseUnit Unit2 = Player::parsePlayer(argv[2]);
Itt inkább a `BaseUnit::parseUnit`ot kellene meghívni, mert most egy `Player`t próbál eltárolni egy `BaseUnit` változóban. Hibát nem okoz, mert az extra tagváltozókat levágja, de azért nem szép. Csodálom is, hogy nem ír rá warningot a fordító.

2020-10-14 13:45 UTC, oliverosz commented on main.cpp
> +		BaseUnit Unit2 = Player::parseUnit(argv[2]);
OK, de akkor már inkább `BaseUnit::parseUnit`

2020-10-14 13:46 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: cppcheck *.cpp --enable=warning,style,performance --error-exitcode=1
Ahol elkaszálja a workflow-t, oda elég a warning

2020-10-14 13:58 UTC, molmat commented on .github/workflows/test.yml
> +        run: cppcheck *.cpp --enable=warning,style,performance --error-exitcode=1
kijavítottam a performance hibákat amiket dobott így maradhat bent vagy inkább írjam át hogy a későbbiekben ne legyen gond?

2020-10-14 14:06 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: cppcheck *.cpp --enable=warning,style,performance --error-exitcode=1
Írd át. A jelenlegi verziónak nem sok értelme van, így soha nem fog semmit feltölteni artifactként.

2020-10-14 14:06 UTC, molmat commented on .github/workflows/test.yml
> +        run: cppcheck *.cpp --enable=warning,style,performance --error-exitcode=1
közben rájöttem hogy akkor nem sok értelme lenne az artifactolásnak utána

2020-10-14 14:07 UTC, oliverosz approved these changes

2020-10-14 14:09 UTC, oliverosz commented
Most már rendben van, csak frissíteni kell a masterre, és feloldani a conflictokat.

2020-10-16 04:44 UTC, kalmar-adam commented
@oliverosz Merge? Vagy ez következő heti projekt?

2020-10-16 17:37 UTC, oliverosz requested changes
Mergelném én masterbe, de sajnos a branch update nem sikerült hibátlanul.

2020-10-16 17:37 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: cppcheck *.cpp --enable=warning --output-file=checkreport.txt
Ez a javítás elveszett a merge során.

2020-10-16 17:37 UTC, oliverosz commented on .github/workflows/test.yml
> +        run: valgrind --error-exitcode=1 ./a.out units/unit1.json units/unit2.json
Ez is.

2020-10-16 17:37 UTC, oliverosz commented on BaseUnit.h
> +    virtual void causeDamage(BaseUnit*);
Ezek is kapjanak dokumentációt.

2020-10-16 17:37 UTC, oliverosz commented on README.md
> -link: https://teaching-projects.github.io/SZE-MOSZE-2020-TeamlessName/
Gondolom ez is véletlenül törlődött merge közben.

2020-10-17 04:17 UTC, kalmar-adam commented
Amikor a levelup branchet megpróbálom rebaselni a jelenlegi masterre akkor még conflictol és valószínűleg ez a hiba/ok áll az eltűnő kódrészletek mögött. Megpróbálom rebase-el fixelni.

2020-10-17 07:32 UTC, kalmar-adam commented
@oliverosz 
A sikeres (levelup -> attackpeed-es master) merge-t megelőzően már képesnek kell lennie az attackspeed kezelésére is igaz?

2020-10-17 10:28 UTC, oliverosz commented
> @oliverosz
> A sikeres (levelup -> attackpeed-es master) merge-t megelőzően már képesnek kell lennie az attackspeed kezelésére is igaz?

Nem teljesen értem a kérdést. A masteren már elvileg ott van az attackspeed kezelése. A merge az a két branch egyesítése. Tehát ezután az egyesített branchen mindkét feature-nek működnie kell. Most még a levelup az egyesített branch, de mindjárt bemergelem masterre, és akkor ott is az egyesített állapot lesz.

2020-10-17 10:29 UTC, oliverosz approved these changes

2020-10-17 10:29 UTC, merged

2020-10-17 10:30 UTC, kalmar-adam commented
> 
> 
> > @oliverosz
> > A sikeres (levelup -> attackpeed-es master) merge-t megelőzően már képesnek kell lennie az attackspeed kezelésére is igaz?
> 
> Nem teljesen értem a kérdést. A masteren már elvileg ott van az attackspeed kezelése. A merge az a két branch egyesítése. Tehát ezután az egyesített branchen mindkét feature-nek működnie kell. Most még a levelup az egyesített branch, de mindjárt bemergelem masterre, és akkor ott is az egyesített állapot lesz.

Ja igen látom, értem. Elnézést kérek!